const mongoose = require("mongoose")

const orderSchema= new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            require:true
        },
        phoneNumber:{
            type:Number,
            require:true
        }
    },
    orderItems:[
       { 
        name:{
            type:String,
            required:true
        },
        quantity:{
            type:Number,
            required:true,
            default:1
        },
        price:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
            type:mongoose.Schema.ObjectId,
            ref:"Product",
            require:true
        }
     }
    ],
    user:{
        type:mongoose.Schema.ObjectId, 
        ref:"User",
        required:true
     },
     paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }
     },
     paidAt:{
        type:Date,
        required:true
     },
     itemsPrice:{
        type:Number,
        default:0,
        require:true,
     },
     taxPrice:{
        type:Number,
        default:0,
        require:true,
     },
     shippingPrice:{
        type:Number,
        default:0,
        require:true,
     },
     totalPrice:{
        type:Number,
        require:true,
        default:0
     },
     orderStatus:{
        type:String,
        default:"Processing"
     },
     deliveredAt:Date,
     createdAt:{
        type:Date,
        default:Date.now
     }
})

module.exports =mongoose.model("Order", orderSchema)
